server:
  port: ${SERVER-PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${DB-URL}/trello
    username: ${DB-USER}
    password: ${DB-PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: ${DDL-AUTO}
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        connection:
          CharSet: utf-8
          characterEncoding: utf-8
          useUnicode: true

logging.level:
  root: info
#  org.hibernate.SQL: debug
#  org.springframework.security: debug
#  org.springframework.web: debug

jwt-secret-key: ${JWT-SECRET-KEY}
admin-password: ${MANAGER-PASSWORD}

cloud:
  aws:
    credentials:
      access-key: ${AWS-ACCESS-KEY}
      secret-key: ${AWS-SECRET-KEY}
    region:
      static: us-east-2
    s3:
      bucket: sparta-storage

kakao:
  client-id: ${CLIENT-ID}
  redirect-uri: http://localhost:8080/users/kakao/callback

